### ISSUE TITLE
关于扩散模型在训练和预测过程的输入

### ISSUE THREAD

**Issue by dzyanshan** [Lenubolim/TextDiff#1]
您好！我阅读了您的论文，但在某些部分我还有一些理解上的困惑。因此，我希望能够向您请教并解答一些疑问。非常感谢您的时间和帮助！
我看到您在扩散模型的训练过程中，给出的公式中xt是由xres加噪获取的图像，这里为什么可以将GT的信息（GT减去SR）作为模型训练的条件？在预测过程中，这部分依旧是xres吗，还是其他的内容？

**Comment by Lenubolim** [comment]
这是来自QQ邮箱的自动回复邮件。你好，你的邮件我已收到。

**Comment by Lenubolim** [comment]
> 您好！我阅读了您的论文，但在某些部分我还有一些理解上的困惑。因此，我希望能够向您请教并解答一些疑问。非常感谢您的时间和帮助！ 我看到您在扩散模型的训练过程中，给出的公式中xt是由xres加噪获取的图像，这里为什么可以将GT的信息（GT减去SR）作为模型训练的条件？在预测过程中，这部分依旧是xres吗，还是其他的内容？

预测仍然是残差信息

**Comment by dzyanshan** [comment]
感谢解答！还有一点疑惑，请问预测的时候是没有GT的，残差信息是如何获取的？

**Comment by dzyanshan** [comment]
> > 您好！我阅读了您的论文，但在某些部分我还有一些理解上的困惑。因此，我希望能够向您请教并解答一些疑问。非常感谢您的时间和帮助！ 我看到您在扩散模型的训练过程中，给出的公式中xt是由xres加噪获取的图像，这里为什么可以将GT的信息（GT减去SR）作为模型训练的条件？在预测过程中，这部分依旧是xres吗，还是其他的内容？
> 
> 预测仍然是残差信息

感谢解答！还有一点疑惑，请问预测的时候是没有GT的，残差信息是如何获取的？

**Comment by Lenubolim** [comment]
> > > 您好！我阅读了您的论文，但在某些部分我还有一些理解上的困惑。因此，我希望能够向您请教并解答一些疑问。非常感谢您的时间和帮助！ 我看到您在扩散模型的训练过程中，给出的公式中xt是由xres加噪获取的图像，这里为什么可以将GT的信息（GT减去SR）作为模型训练的条件？在预测过程中，这部分依旧是xres吗，还是其他的内容？
> > 
> > 
> > 预测仍然是残差信息
> 
> 感谢解答！还有一点疑惑，请问预测的时候是没有GT的，残差信息是如何获取的？

预测的时候不需要GT,根据训练的原理，预测的就是残差信息，在论文中原理部分及算法伪代码部分有所提及，您可以阅读该部分内容。

**Comment by 649459021** [comment]
![Snipaste_2023-11-30_15-53-05](https://github.com/Lenubolim/TextDiff/assets/49975880/6a437a20-4b05-45f5-a752-085950192d91)

UNet的输入这里是 残差还是一阶段网络的x_sr呢？   按照伪代码应该是x_sr吧

**Comment by Lenubolim** [comment]
这是来自QQ邮箱的自动回复邮件。你好，你的邮件我已收到。

**Comment by Lenubolim** [comment]
> ![Snipaste_2023-11-30_15-53-05](https://private-user-images.githubusercontent.com/49975880/286855957-6a437a20-4b05-45f5-a752-085950192d91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMzEzODksIm5iZiI6MTcwMTMzMTA4OSwicGF0aCI6Ii80OTk3NTg4MC8yODY4NTU5NTctNmE0MzdhMjAtNGIwNS00NWY1LWE3NTItMDg1OTUwMTkyZDkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA3NTgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmOGU1MzFhMjQyMGY3ZDA5YmQ0ZTM2Y2VmZjg0MGUzNzkyNmM4MmI2ZWVhZWFiNjYwNzEwODllMGMxZTI3MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9VwifOjPw7TYEoIV5ZEXA-CU2tOVOWhL3dzkuolxPCY)
> 
> UNet的输入这里是 残差还是一阶段网络的x_sr呢？ 按照伪代码应该是x_sr吧

在训练部分的伪代码中，输入是残差信息

**Comment by 649459021** [comment]
> > ![Snipaste_2023-11-30_15-53-05](https://private-user-images.githubusercontent.com/49975880/286855957-6a437a20-4b05-45f5-a752-085950192d91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMzEzODksIm5iZiI6MTcwMTMzMTA4OSwicGF0aCI6Ii80OTk3NTg4MC8yODY4NTU5NTctNmE0MzdhMjAtNGIwNS00NWY1LWE3NTItMDg1OTUwMTkyZDkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA3NTgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmOGU1MzFhMjQyMGY3ZDA5YmQ0ZTM2Y2VmZjg0MGUzNzkyNmM4MmI2ZWVhZWFiNjYwNzEwODllMGMxZTI3MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9VwifOjPw7TYEoIV5ZEXA-CU2tOVOWhL3dzkuolxPCY)
> > UNet的输入这里是 残差还是一阶段网络的x_sr呢？ 按照伪代码应该是x_sr吧
> 
> 在训练部分的伪代码中，输入是残差信息

诶，在推理过程中，没有GT，UNet输入的残差信息从哪得到呢，是谁和x_sr来计算残差

**Comment by Lenubolim** [comment]
> > > ![Snipaste_2023-11-30_15-53-05](https://private-user-images.githubusercontent.com/49975880/286855957-6a437a20-4b05-45f5-a752-085950192d91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMzEzODksIm5iZiI6MTcwMTMzMTA4OSwicGF0aCI6Ii80OTk3NTg4MC8yODY4NTU5NTctNmE0MzdhMjAtNGIwNS00NWY1LWE3NTItMDg1OTUwMTkyZDkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA3NTgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmOGU1MzFhMjQyMGY3ZDA5YmQ0ZTM2Y2VmZjg0MGUzNzkyNmM4MmI2ZWVhZWFiNjYwNzEwODllMGMxZTI3MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9VwifOjPw7TYEoIV5ZEXA-CU2tOVOWhL3dzkuolxPCY)
> > > UNet的输入这里是 残差还是一阶段网络的x_sr呢？ 按照伪代码应该是x_sr吧
> > 
> > 
> > 在训练部分的伪代码中，输入是残差信息
> 
> 诶，在推理过程中，没有GT，UNet输入的残差信息从哪得到呢，是谁和x_sr来计算残差

如论文中推理伪代码所示，输入不需要残差信息，您可参考论文《Deblurring via Stochastic Refinement》

**Comment by Lenubolim** [comment]
> > > ![Snipaste_2023-11-30_15-53-05](https://private-user-images.githubusercontent.com/49975880/286855957-6a437a20-4b05-45f5-a752-085950192d91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMzEzODksIm5iZiI6MTcwMTMzMTA4OSwicGF0aCI6Ii80OTk3NTg4MC8yODY4NTU5NTctNmE0MzdhMjAtNGIwNS00NWY1LWE3NTItMDg1OTUwMTkyZDkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA3NTgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmOGU1MzFhMjQyMGY3ZDA5YmQ0ZTM2Y2VmZjg0MGUzNzkyNmM4MmI2ZWVhZWFiNjYwNzEwODllMGMxZTI3MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9VwifOjPw7TYEoIV5ZEXA-CU2tOVOWhL3dzkuolxPCY)
> > > UNet的输入这里是 残差还是一阶段网络的x_sr呢？ 按照伪代码应该是x_sr吧
> > 
> > 
> > 在训练部分的伪代码中，输入是残差信息
> 
> 诶，在推理过程中，没有GT，UNet输入的残差信息从哪得到呢，是谁和x_sr来计算残差

如论文中推理伪代码所示，输入不需要残差信息，您可参考论文《Deblurring via Stochastic Refinement》

**Comment by 649459021** [comment]
> > > > ![Snipaste_2023-11-30_15-53-05](https://private-user-images.githubusercontent.com/49975880/286855957-6a437a20-4b05-45f5-a752-085950192d91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMzEzODksIm5iZiI6MTcwMTMzMTA4OSwicGF0aCI6Ii80OTk3NTg4MC8yODY4NTU5NTctNmE0MzdhMjAtNGIwNS00NWY1LWE3NTItMDg1OTUwMTkyZDkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA3NTgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmOGU1MzFhMjQyMGY3ZDA5YmQ0ZTM2Y2VmZjg0MGUzNzkyNmM4MmI2ZWVhZWFiNjYwNzEwODllMGMxZTI3MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9VwifOjPw7TYEoIV5ZEXA-CU2tOVOWhL3dzkuolxPCY)
> > > > UNet的输入这里是 残差还是一阶段网络的x_sr呢？ 按照伪代码应该是x_sr吧
> > > 
> > > 
> > > 在训练部分的伪代码中，输入是残差信息
> > 
> > 
> > 诶，在推理过程中，没有GT，UNet输入的残差信息从哪得到呢，是谁和x_sr来计算残差
> 
> 如论文中推理伪代码所示，输入不需要残差信息，您可参考论文《Deblurring via Stochastic Refinement》

这篇论文并没有把residual 拼接到UNet的输入中去吧，只是用来作为x_0。TextDiff图3中看起来是把residual通过concatenate到UNet的输入中，不知这里我是否理解有误。

若对residual的处理和DocDiff相同的话，则是图3引起了误解

**Comment by Lenubolim** [comment]
> > > > > ![Snipaste_2023-11-30_15-53-05](https://private-user-images.githubusercontent.com/49975880/286855957-6a437a20-4b05-45f5-a752-085950192d91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMzEzODksIm5iZiI6MTcwMTMzMTA4OSwicGF0aCI6Ii80OTk3NTg4MC8yODY4NTU5NTctNmE0MzdhMjAtNGIwNS00NWY1LWE3NTItMDg1OTUwMTkyZDkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA3NTgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmOGU1MzFhMjQyMGY3ZDA5YmQ0ZTM2Y2VmZjg0MGUzNzkyNmM4MmI2ZWVhZWFiNjYwNzEwODllMGMxZTI3MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9VwifOjPw7TYEoIV5ZEXA-CU2tOVOWhL3dzkuolxPCY)
> > > > > UNet的输入这里是 残差还是一阶段网络的x_sr呢？ 按照伪代码应该是x_sr吧
> > > > 
> > > > 
> > > > 在训练部分的伪代码中，输入是残差信息
> > > 
> > > 
> > > 诶，在推理过程中，没有GT，UNet输入的残差信息从哪得到呢，是谁和x_sr来计算残差
> > 
> > 
> > 如论文中推理伪代码所示，输入不需要残差信息，您可参考论文《Deblurring via Stochastic Refinement》
> 
> 这篇论文并没有把residual 拼接到UNet的输入中去吧，只是用来作为x_0。TextDiff图3中看起来是把residual通过concatenate到UNet的输入中，不知这里我是否理解有误。
> 
> 若对residual的处理和DocDiff相同的话，则是图3引起了误解

不好意思，确实描述不清，这是我们的疏忽，将在下一版本中更改网络结构图。

**Comment by 649459021** [comment]
> > > > > > ![Snipaste_2023-11-30_15-53-05](https://private-user-images.githubusercontent.com/49975880/286855957-6a437a20-4b05-45f5-a752-085950192d91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMzEzODksIm5iZiI6MTcwMTMzMTA4OSwicGF0aCI6Ii80OTk3NTg4MC8yODY4NTU5NTctNmE0MzdhMjAtNGIwNS00NWY1LWE3NTItMDg1OTUwMTkyZDkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA3NTgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmOGU1MzFhMjQyMGY3ZDA5YmQ0ZTM2Y2VmZjg0MGUzNzkyNmM4MmI2ZWVhZWFiNjYwNzEwODllMGMxZTI3MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9VwifOjPw7TYEoIV5ZEXA-CU2tOVOWhL3dzkuolxPCY)
> > > > > > UNet的输入这里是 残差还是一阶段网络的x_sr呢？ 按照伪代码应该是x_sr吧
> > > > > 
> > > > > 
> > > > > 在训练部分的伪代码中，输入是残差信息
> > > > 
> > > > 
> > > > 诶，在推理过程中，没有GT，UNet输入的残差信息从哪得到呢，是谁和x_sr来计算残差
> > > 
> > > 
> > > 如论文中推理伪代码所示，输入不需要残差信息，您可参考论文《Deblurring via Stochastic Refinement》
> > 
> > 
> > 这篇论文并没有把residual 拼接到UNet的输入中去吧，只是用来作为x_0。TextDiff图3中看起来是把residual通过concatenate到UNet的输入中，不知这里我是否理解有误。
> > 若对residual的处理和DocDiff相同的话，则是图3引起了误解
> 
> 不好意思，确实描述不清，这是我们的疏忽，将在下一版本中更改网络结构图。

多谢作者的及时回复~     ：）
