### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by 649459021** [Lenubolim/TextDiff#2]
Hi,

This is a nice work!  Is there a plan to release the code?

Thanks

**Comment by Lenubolim** [comment]
Thank you very much for your affirmation! Yes, we plan to open source the code so more people can use and contribute. As soon as the code is ready, we will publish the open source information here. Please follow us for updates. Also, feel free to contact us if you have any other questions or suggestions.

**Comment by Lenubolim** [comment]
> Hi,
> 
> This is a nice work! Is there a plan to release the code?
> 
> Thanks

Thank you very much for your affirmation! Yes, we plan to open source the code so more people can use and contribute. As soon as the code is ready, we will publish the open source information here. Please follow us for updates. Also, feel free to contact us if you have any other questions or suggestions.
