### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by 649459021** [Lenubolim/TextDiff#3]
作者您好，
我在尝试自行复现的过程中遇到以下几点疑惑：

1. 论文中报告DocDiff在TextZoom数据集的aster识别平均正确率只有56%，与我跑的结果相似，您认为是什么原因导致DocDiff在该数据集上表现不佳呢？
2. 您是否尝试过在输入网络前对图片进行STN，该操作对识别率影响大嘛？
3. 您是否尝试过在TextZoom上不使用第一阶段的CNN而是直接训练ddpm呢，效果是否有明显下降？

期待您的回复~

**Comment by Lenubolim** [comment]
1. 需要考虑场景文字结构特征
2. 为了增强网络的鲁棒性，该操作在TextDiff未被采用
3. 暂时未尝试

> 作者您好， 我在尝试自行复现的过程中遇到以下几点疑惑：
> 
> 1. 论文中报告DocDiff在TextZoom数据集的aster识别平均正确率只有56%，与我跑的结果相似，您认为是什么原因导致DocDiff在该数据集上表现不佳呢？
> 2. 您是否尝试过在输入网络前对图片进行STN，该操作对识别率影响大嘛？
> 3. 您是否尝试过在TextZoom上不使用第一阶段的CNN而是直接训练ddpm呢，效果是否有明显下降？
> 
> 期待您的回复~

1. 需要考虑场景文字结构特征
2. 为了增强网络的鲁棒性，该操作在TextDiff未被采用
3. 暂时未尝试

**Comment by Lenubolim** [comment]
> 作者您好， 我在尝试自行复现的过程中遇到以下几点疑惑：
> 
> 1. 论文中报告DocDiff在TextZoom数据集的aster识别平均正确率只有56%，与我跑的结果相似，您认为是什么原因导致DocDiff在该数据集上表现不佳呢？
> 2. 您是否尝试过在输入网络前对图片进行STN，该操作对识别率影响大嘛？
> 3. 您是否尝试过在TextZoom上不使用第一阶段的CNN而是直接训练ddpm呢，效果是否有明显下降？
> 
> 期待您的回复~

1. 需要考虑场景文字结构特征
2. 为了增强网络的鲁棒性，该操作在TextDiff未被采用
3. 暂时未尝试

**Comment by 649459021** [comment]
感谢~
