### ISSUE TITLE
Fantastic work! When will the  inference code  be published?

### ISSUE THREAD

**Issue by msk7131** [Lenubolim/TextDiff#5]
Fantastic work! When will the  inference code  be published?

**Comment by Lenubolim** [comment]
这是来自QQ邮箱的自动回复邮件。你好，你的邮件我已收到。

**Comment by Lenubolim** [comment]
Due to some reasons, the development has been delayed, please wait, thank you. Or you can use DocDiff to help you reproduce our paper.
