### ISSUE TITLE
Request for Open Sourcing Weights and Code

### ISSUE THREAD

**Issue by cwzzzzz** [Lenubolim/TextDiff#7]
Dear Lenubolim,
     I hope this email finds you well. I am reaching out to you from BUAA. I am writing to express my keen interest in your recent publication titled "TextDiff",  I believe that your work holds significant potential to greatly assist me in my current research, and I am eager to explore it further.
    In light of this, I kindly request your consideration in open-sourcing the weights and code associated with your research. I assure you that any insights gained or progress made as a result of accessing your resources will be duly acknowledged in any subsequent publications or presentations.
    I understand the importance of intellectual property rights and assure you that the usage of your code and weights will be strictly for academic and research purposes. Any terms or conditions you may have regarding the sharing of these resources will be fully respected and adhered to.
    Thank you very much for considering my request. I look forward to your favorable response. Please do not hesitate to reach out if you require any further information or clarification.

Warm regards,
cwz@buaa.edu.cn

**Comment by Lenubolim** [comment]
这是来自QQ邮箱的自动回复邮件。你好，你的邮件我已收到。

**Comment by Lenubolim** [comment]
Due to some reasons, the development has been delayed, please wait, thank you. Or you can use DocDiff to help you reproduce our paper. 

Best wishes!
